### ISSUE TITLE
Alter frontpage examples to replace deprecated `explode` command with `all`

### ISSUE THREAD

**Issue by crinklywrappr** [elves/elvish#1101]
For example

```
~> curl https://api.github.com/repos/elves/elvish/issues |
     from-json | explode (all) |
     each [issue]{ echo $issue[number]: $issue[title] } |
     head -n 11
366: Support searching file from elvish directly
364: Ctrl-C in elvish kills Atom in background
357: Asynchronous syntax highlighting
356: In web backend, run commands with pty IO, not pipe
354: Support multi-line prompts from byte output
353: Completers should detect context in a top-down manner
352: Quoted command names are highlighted randomly
351: keep navigation mode open after command
350: Raw mode requires two presses of ^V
344: Elvish won't compile
343: Possible to suppress job control messages?
```

**Comment by zzamboni** [comment]
Actually that command still includes `explode`. It might be replaced with `all (all)`, but that seems a bit wonky. How about this one:
```
[~]|> curl -s https://api.github.com/repos/elves/elvish/issues |
        from-json | all (one) |
        each [issue]{ echo $issue[number]: $issue[title] } |
        head -n 11
1101: Alter frontpage examples to replace deprecated `explode` command with `all`
1100: Add `randint` command unit tests
1099: `/` (division command) invoked with no args does `cd /`
1098: Convert "XXX" to "TODO" comments
1097: Add explicit `cd` unit tests
1096: Add basic tests for the *-external builtins
1095: Validate a for loop corner case
1094: Eliminate sys.Ioctl
1093: Increase umask code coverage from 62% to 100%
1092: Fix `exec` handling of $E:SHLVL
1091: `exec` command needs to special-case `$E:SHLVL`
```

**Comment by zzamboni** [comment]
Or maybe even better, remove the use of `echo` and `head` and leave only internal commands:
```
[~]|> curl -s https://api.github.com/repos/elves/elvish/issues |
        from-json | all (one) |
        each [issue]{ put $issue[number]": "$issue[title] } |
        take 11
▶ '1101: Alter frontpage examples to replace deprecated `explode` command with `all`'
▶ '1100: Add `randint` command unit tests'
▶ '1099: `/` (division command) invoked with no args does `cd /`'
▶ '1098: Convert "XXX" to "TODO" comments'
▶ '1097: Add explicit `cd` unit tests'
▶ '1096: Add basic tests for the *-external builtins'
▶ '1095: Validate a for loop corner case'
▶ '1094: Eliminate sys.Ioctl'
▶ '1093: Increase umask code coverage from 62% to 100%'
▶ '1092: Fix `exec` handling of $E:SHLVL'
▶ '1091: `exec` command needs to special-case `$E:SHLVL`'
```

**Comment by crinklywrappr** [comment]
The example is supposed to demonstrate marshalling data between both pipelines, and the first example appears to do more of that, so I think it's a bit better.

**Comment by krader1961** [comment]
@crinklywrappr, Can you elaborate on your last comment? @zzamboni's second example is identical to his first other than replacing the external `head` with the builtin `take` command. Both examples "demonstrate marshalling data between both pipelines" AFAICT.

It took me a bit of sleuthing to realize you're talking about the example found in file *website/ttyshot/pipelines.html* that shows up as the first example on the https://elv.sh/ web page. Primarily because that example is written in HTML rather than Markdown syntax; which made it much harder to find using traditional search tools like `grep`.

I would argue it's even more important for these examples to be written using the `elvish-transcript` verbatim syntax used elsewhere in the source code for builtin commands rather than raw HTML.

**Comment by krader1961** [comment]
@zzamboni, I think the `from-json | all (one)` in your example is extremely subtle and needs some clarifying commentary. It is relying on the fact that `from-json` in that example is emitting a a single Elvish list, **with zero or more elements**, to the value (not byte) channel. It is "unwrapping" the list to expose the interior elements -- one at a time to its downstream consumer; i.e., the right-hand side of the `all (one) |` pipeline. This is deep magic to most people.

**Comment by crinklywrappr** [comment]
> you elaborate on your last comment?

I only mean that using head to consume data from the byte channel makes it clear that data has been "round-tripped" in and out of the value channel.

**Comment by krader1961** [comment]
@crinklywrappr, I see what you mean. However, the scenario you describe is normally addressed by including an explicit `to-lines` in the pipeline to convert value to byte output. The only reason @zzamboni's first example illustrates your point is because the `each` function uses `echo` rather `put` to write to the byte stream rather than the value stream.

**Comment by crinklywrappr** [comment]
I've never used `to-lines`, but based on that I would guess `... | each [issue] { put ... } | to-lines | head` would be more idiomatic, while still retaining the call to `head`.

**Comment by xiaq** [comment]
Normally using `take 11` would be more idiomatic than `head`, but this pipeline is intended to showcase the interoperability between value pipes and byte pipes, so I'll keep that.

I'll just change `explode (all)` to `all (one)`. Yes it's a bit non-ideal that the example requires some delicate pipeline manipulation, but it still showcases the first-class for JSON and using `each` for iteration. The overall idea of what this pipeline does is still, hopefully, quite straightforward to understand.

@krader1961 these "ttyshots" unfortunately can't be written using `elvish-transcript` since some of them contain UI elements.

**Comment by krader1961** [comment]
> these "ttyshots" unfortunately can't be written using elvish-transcript since some of them contain UI elements.

Understood, @xiaq, but it would greatly help if they also contained a HTML comment that contained the raw  Elvish script.

**Comment by xiaq** [comment]
@krader1961 I'm not sure how useful that'd be other than making it easier to search - it also introduces manual maintenance labor since there is no way to ensure that the HTML and the comment are in sync.

**Comment by krader1961** [comment]
> I'm not sure how useful that'd be other than making it easier to search...

That's the primary reason to do so -- see my earlier [comment](https://github.com/elves/elvish/issues/1101#issuecomment-671737443). I haven't looked at the `edit:-dump-buf` command that produces these files. But presumably "it's just a small matter of writing some code" (trademark) to have that command also include a HTML comment with the raw CLI text.
